extends:
  - '@wordpress/stylelint-config/scss'
rules:
  # Prettier automatically removes the empty line
  at-rule-empty-line-before: null
  rule-empty-line-before: null
  declaration-colon-newline-after: null
  # Allow BEM style classes
  selector-class-pattern: null
